# Generated by Django 4.1 on 2022-09-07 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                ("title", models.CharField(blank=True, max_length=200, null=True)),
                ("ownerWallet", models.CharField(default="Locked", max_length=200)),
                ("forSale", models.CharField(default="No", max_length=200)),
                ("uniqueId", models.IntegerField(primary_key=True, serialize=False)),
                ("tradeId", models.CharField(blank=True, max_length=100, null=True)),
                ("date_created", models.DateTimeField(blank=True, null=True)),
                ("last_updated", models.DateTimeField(blank=True, null=True)),
                (
                    "img_photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="unlocked_buffs/"
                    ),
                ),
                ("img_url", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ImageTwo",
            fields=[
                ("id", models.IntegerField(blank=True)),
                ("title", models.CharField(blank=True, max_length=200, null=True)),
                ("ownerWallet", models.CharField(default="Locked", max_length=200)),
                ("forSale", models.CharField(default="No", max_length=200)),
                (
                    "uniqueId",
                    models.IntegerField(blank=True, primary_key=True, serialize=False),
                ),
                ("tradeId", models.CharField(blank=True, max_length=100, null=True)),
                ("date_created", models.DateTimeField(blank=True, null=True)),
                ("last_updated", models.DateTimeField(blank=True, null=True)),
                (
                    "img_photo",
                    models.ImageField(
                        blank=True, null=True, upload_to="unlocked_buffs/"
                    ),
                ),
                ("img_url", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Trait",
            fields=[
                (
                    "uniqueId",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="traits",
                        serialize=False,
                        to="main.image",
                    ),
                ),
                ("total_buff_score", models.IntegerField(blank=True, null=True)),
                (
                    "background_feature",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "background_feature_rarity",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "background_specific",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("background_buff_score", models.IntegerField(blank=True, null=True)),
                (
                    "fur_feature",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "fur_feature_rarity",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "fur_specific",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("fur_buff_score", models.IntegerField(blank=True, null=True)),
                (
                    "swag_feature",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "swag_feature_rarity",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "swag_specific",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("swag_buff_score", models.IntegerField(blank=True, null=True)),
                (
                    "horns_feature",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "horns_feature_rarity",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "horns_specific",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("horns_buff_score", models.IntegerField(blank=True, null=True)),
                (
                    "eyes_feature",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "eyes_feature_rarity",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "eyes_specific",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("eyes_buff_score", models.IntegerField(blank=True, null=True)),
                (
                    "mouth_feature",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "mouth_feature_rarity",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "mouth_specific",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("mouth_buff_score", models.IntegerField(blank=True, null=True)),
                ("smoking", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "smoking_rarity",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("smoking_buff_score", models.IntegerField(blank=True, null=True)),
                (
                    "double_baby_buff",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "double_baby_buff_rarity",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "double_baby_buff_buff_score",
                    models.IntegerField(blank=True, null=True),
                ),
                ("cyborg", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "cyborg_rarity",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("cyborg_buff_score", models.IntegerField(blank=True, null=True)),
                ("cowboy", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "cowboy_rarity",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("cowboy_buff_score", models.IntegerField(blank=True, null=True)),
                ("dbz", models.CharField(blank=True, max_length=200, null=True)),
                ("dbz_rarity", models.CharField(blank=True, max_length=200, null=True)),
                ("dbz_buff_score", models.IntegerField(blank=True, null=True)),
                ("matrix", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "matrix_rarity",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("matrix_buff_score", models.IntegerField(blank=True, null=True)),
                ("nono", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "nono_rarity",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("nono_buff_score", models.IntegerField(blank=True, null=True)),
                ("undead", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "undead_rarity",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("undead_buff_score", models.IntegerField(blank=True, null=True)),
                ("albino", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "albino_rarity",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("albino_buff_score", models.IntegerField(blank=True, null=True)),
                (
                    "rice_farmer",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "rice_farmer_rarity",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("rice_farmer_buff_score", models.IntegerField(blank=True, null=True)),
                ("super_hero", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "super_hero_rarity",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("super_hero_buff_score", models.IntegerField(blank=True, null=True)),
                ("trippy", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "trippy_rarity",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("trippy_buff_score", models.IntegerField(blank=True, null=True)),
                ("gentleman", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "gentleman_rarity",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("gentleman_buff_score", models.IntegerField(blank=True, null=True)),
                (
                    "joseph_smith",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "joseph_smith_rarity",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("joseph_smith_buff_score", models.IntegerField(blank=True, null=True)),
                ("day_walker", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "day_walker_rarity",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("day_walker_buff_score", models.IntegerField(blank=True, null=True)),
                ("jordan", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "jordan_rarity",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("jordan_buff_score", models.IntegerField(blank=True, null=True)),
                (
                    "hells_kitchen",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "hells_kitchen_rarity",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "hells_kitchen_buff_score",
                    models.IntegerField(blank=True, null=True),
                ),
                ("golded", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "golded_rarity",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("golded_buff_score", models.IntegerField(blank=True, null=True)),
                ("girl", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "girl_rarity",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("girl_buff_score", models.IntegerField(blank=True, null=True)),
                ("rasta", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "rasta_rarity",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("rasta_buff_score", models.IntegerField(blank=True, null=True)),
                ("radix", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "radix_rarity",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("radix_buff_score", models.IntegerField(blank=True, null=True)),
                ("bloody", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "bloody_rarity",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("bloody_buff_score", models.IntegerField(blank=True, null=True)),
                ("bamf", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "bamf_rarity",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("bamf_buff_score", models.IntegerField(blank=True, null=True)),
                ("frat_buff", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "frat_buff_rarity",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("frat_buff_buff_score", models.IntegerField(blank=True, null=True)),
                ("demigod", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "demigod_rarity",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("demigod_buff_score", models.IntegerField(blank=True, null=True)),
                ("regrets", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "regrets_rarity",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("regrets_buff_score", models.IntegerField(blank=True, null=True)),
                ("raver", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "raver_rarity",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("raver_buff_score", models.IntegerField(blank=True, null=True)),
                (
                    "kiddie_pool",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "kiddie_pool_rarity",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("kiddie_pool_buff_score", models.IntegerField(blank=True, null=True)),
                ("mutated", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "mutated_rarity",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("mutated_buff_score", models.IntegerField(blank=True, null=True)),
                ("half_dead", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "half_dead_rarity",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("half_dead_buff_score", models.IntegerField(blank=True, null=True)),
                ("oversized", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "oversized_rarity",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("oversized_buff_score", models.IntegerField(blank=True, null=True)),
                (
                    "easter_celebration",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "easter_celebration_rarity",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "easter_celebration_buff_score",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "brads_and_chads",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "brads_and_chads_rarity",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "brads_and_chads_buff_score",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "chromed_out",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "chromed_out_rarity",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("chromed_out_buff_score", models.IntegerField(blank=True, null=True)),
                (
                    "natural_evolution",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "natural_evolution_rarity",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "natural_evolution_buff_score",
                    models.IntegerField(blank=True, null=True),
                ),
                ("pride", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "pride_rarity",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("pride_buff_score", models.IntegerField(blank=True, null=True)),
                (
                    "buffs_mafia",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "buffs_mafia_rarity",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("buffs_mafia_buff_score", models.IntegerField(blank=True, null=True)),
                ("agent_zero", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "agent_zero_rarity",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("agent_zero_buff_score", models.IntegerField(blank=True, null=True)),
                ("family_guy", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "family_guy_rarity",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("family_guy_buff_score", models.IntegerField(blank=True, null=True)),
                ("playboy", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "playboy_rarity",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("playboy_buff_score", models.IntegerField(blank=True, null=True)),
                (
                    "battle_hardened",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "battle_hardened_rarity",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "battle_hardened_buff_score",
                    models.IntegerField(blank=True, null=True),
                ),
                ("fire", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "fire_rarity",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("fire_buff_score", models.IntegerField(blank=True, null=True)),
                (
                    "collections",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "collections_name",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "collections_rarity",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("collections_buff_score", models.IntegerField(blank=True, null=True)),
                ("green", models.CharField(blank=True, max_length=200, null=True)),
                ("green_num", models.IntegerField(blank=True, null=True)),
                (
                    "green_rarity",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("green_buff_score", models.IntegerField(blank=True, null=True)),
                ("red", models.CharField(blank=True, max_length=200, null=True)),
                ("red_num", models.IntegerField(blank=True, null=True)),
                ("red_rarity", models.CharField(blank=True, max_length=200, null=True)),
                ("red_buff_score", models.IntegerField(blank=True, null=True)),
                ("purple", models.CharField(blank=True, max_length=200, null=True)),
                ("purple_num", models.IntegerField(blank=True, null=True)),
                (
                    "purple_rarity",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("purple_buff_score", models.IntegerField(blank=True, null=True)),
                ("blue", models.CharField(blank=True, max_length=200, null=True)),
                ("blue_num", models.IntegerField(blank=True, null=True)),
                (
                    "blue_rarity",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("blue_buff_score", models.IntegerField(blank=True, null=True)),
                ("pink", models.CharField(blank=True, max_length=200, null=True)),
                ("pink_num", models.IntegerField(blank=True, null=True)),
                (
                    "pink_rarity",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("pink_buff_score", models.IntegerField(blank=True, null=True)),
                ("yellow", models.CharField(blank=True, max_length=200, null=True)),
                ("yellow_num", models.IntegerField(blank=True, null=True)),
                (
                    "yellow_rarity",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("yellow_buff_score", models.IntegerField(blank=True, null=True)),
                ("brown", models.CharField(blank=True, max_length=200, null=True)),
                ("brown_num", models.IntegerField(blank=True, null=True)),
                (
                    "brown_rarity",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("brown_buff_score", models.IntegerField(blank=True, null=True)),
                ("black", models.CharField(blank=True, max_length=200, null=True)),
                ("black_num", models.IntegerField(blank=True, null=True)),
                (
                    "black_rarity",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("black_buff_score", models.IntegerField(blank=True, null=True)),
                ("orange", models.CharField(blank=True, max_length=200, null=True)),
                ("orange_num", models.IntegerField(blank=True, null=True)),
                (
                    "orange_rarity",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("orange_buff_score", models.IntegerField(blank=True, null=True)),
                ("matching", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "matching_color",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "matching_rarity",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("matching_buff_score", models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
