# Generated by Django 4.0.2 on 2022-03-08 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
