# Generated by Django 4.1 on 2022-09-12 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="trait",
            name="matching_dictionary",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
