# Generated by Django 4.1 on 2022-09-12 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_trait_matching_dictionary"),
    ]

    operations = [
        migrations.AddField(
            model_name="trait",
            name="collections_dictionary",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
