# Generated by Django 4.0.2 on 2022-03-08 21:50

from django.db import migrations, models
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_images_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='date_created',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='images',
            name='last_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='images',
            name='ownerWallet',
            field=models.CharField(default='Locked', max_length=200),
        ),
        migrations.AddField(
            model_name='images',
            name='slug',
            field=models.SlugField(blank=True, max_length=500, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='images',
            name='uniqueId',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='images',
            name='img_photo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=0, size=[400, 200], upload_to='unlocked_buffs/'),
        ),
    ]
