# Generated by Django 4.1 on 2022-09-22 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_trait_collections_dictionary"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imagetwo",
            name="id",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
