# Generated by Django 4.0.2 on 2022-03-08 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_images_date_created_images_last_updated_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Images',
            new_name='Image',
        ),
    ]
