# Generated by Django 4.0.2 on 2022-03-08 22:06

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_images_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img_photo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=0, size=[2000, 1000], upload_to='unlocked_buffs/'),
        ),
    ]
