# Generated by Django 4.0.2 on 2022-03-08 22:24

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_image_img_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img_photo',
            field=django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=75, size=[1000, 3000], upload_to='unlocked_buffs/'),
        ),
    ]
