# Generated by Django 4.0.2 on 2022-03-09 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_image_img_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='img_photo',
            field=models.ImageField(blank=True, null=True, upload_to='unlocked_buffs/'),
        ),
    ]
