# Generated by Django 4.0.2 on 2022-03-10 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_queries'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Queries',
        ),
    ]
