<<<<<<< HEAD
# Generated by Django 3.2.3 on 2022-06-01 04:33
=======
# Generated by Django 4.0.2 on 2022-06-01 03:19
>>>>>>> d751d5bf24faee59b49fb3b0d43e991a7a33cf4e

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_image_uniqueid'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageTwo',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('ownerWallet', models.CharField(default='Locked', max_length=200)),
                ('uniqueId', models.IntegerField(blank=True, null=True)),
                ('tradeId', models.CharField(blank=True, max_length=100, null=True)),
<<<<<<< HEAD
=======
                ('slug', models.SlugField(blank=True, max_length=500, null=True, unique=True)),
>>>>>>> d751d5bf24faee59b49fb3b0d43e991a7a33cf4e
                ('date_created', models.DateTimeField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(blank=True, null=True)),
                ('img_photo', models.ImageField(blank=True, null=True, upload_to='unlocked_buffs/')),
                ('img_url', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
