# Generated by Django 4.0.2 on 2022-06-22 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_imagetwo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagetwo',
            name='slug',
        ),
        migrations.AddField(
            model_name='image',
            name='forSale',
            field=models.CharField(default='No', max_length=200),
        ),
    ]
