# Generated by Django 4.0.2 on 2022-06-22 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_imagetwo_slug_image_forsale'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagetwo',
            name='forSale',
            field=models.CharField(default='No', max_length=200),
        ),
    ]
